### ISSUE TITLE
convert inch to mm

### ISSUE THREAD

**Issue by 3dsmax4** [avwuff/SVG-to-GCode#2]
hello
i use your soft realese 1.2.4 and i have two questions:
- what do you use software to compile exe (visual basic 5/6/2010...) ?
- i create a svg file in mm and when i create gcode file it stay in inch 

so nice job
best regard

**Comment by avwuff** [comment]
Yup, VB6 is used, it's old but it works!

The software is designed for use only in Inches at this time.  But it will convert your mm to inches.
